---
title: "Lab2"
author: "Ignacio Ayaso"
date: "16/2/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#Definir matrices y vectores
```{r}
print("HolaMundo") #Toda esta zona gris se le denomina "chunck" -> cómodo para hacer pruebas ya que puedes ejecutar chunks (no todo a la vez)
m <- 2
n <- 4
v <- c(2,1,1,8,1,1,2,4)
b <- c(6,4)
A <- matrix(v, nrow = 2, byrow = TRUE) #Solo exite byrow.
AI <- cbind(A, diag(m)) # cbind(X,Y): Concatenar (por columnas)la matriz Y en la matriz X || diag(m) : Matriz identidad de mxm
print(AI)
```


```{r}
calcula_sb <- function(M,J,b){ #Aunk m y n estén en otro chunck se pueden usar dentro de function
  aux <- M[ , J] #J es un vector 
  solucion <- rep(0, m+n) #m+n son la cantidad de columnas que hay (y de variables + holguras !!!!!) || rep(x,y) repite x, y veces
  if(det(aux) == 0){ return(F) }
  
  solucion[J] <- solve(aux, b) #solve devuelve m valores || si pillas columnas no basicas peta el solve
   
  return(solucion) 
}

calcula_sb(AI, c(1,2), b) #c(1,2) es el vector que pilla los valores que hay en las columnas 1 y 2 en la matriz AI

```


```{r}

ncom <- choose(m+n, m) #??????????
combinations(n+m, m) -> C #Combinación de n+m en m es la cantidad de soluciones básicas 
#OJO combinatons es de la librería gtools, hay que instalar desde la pestaña packajes -> install y escribes gtools

for (i in 1 : nrow(C)) { #PARA SACAR TODAS LAS SOLUCIONES BÁSICAS
 sb <- calcula_sb(AI, C[i, ], b)
 print(sb)
}

```